# Generated by Django 3.1.5 on 2021-06-10 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('image', models.ImageField(default='pics/default.jpg', upload_to='pics/docs/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('isgad', models.BooleanField(default=True, editable=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=255)),
                ('image', models.ImageField(default='pics/default.jpg', upload_to='pics/members/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('isgad', models.BooleanField(default=False, editable=False)),
                ('retaled_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.search')),
            ],
        ),
    ]
